# Generated by Django 5.2.6 on 2025-10-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.CharField(default='+994 50 123 45 67', max_length=100),
        ),
    ]
